// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLk2rdO4lmLxwVxkJ3_wlIxv3k1L3y4gs',
    appId: '1:346179915616:web:cc63b8b5d0d2aa3d8d5805',
    messagingSenderId: '346179915616',
    projectId: 'ecommerce-2c6ff',
    authDomain: 'ecommerce-2c6ff.firebaseapp.com',
    storageBucket: 'ecommerce-2c6ff.firebasestorage.app',
    measurementId: 'G-0C3GSZ3Z2Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPpyF0iQstM6Fc6Jy8Ak8QaAj2U-qmge4',
    appId: '1:346179915616:android:9f4d5f66f0d0addd8d5805',
    messagingSenderId: '346179915616',
    projectId: 'ecommerce-2c6ff',
    storageBucket: 'ecommerce-2c6ff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwv8ko-wvJYxDSQpJAinw_7HosRBktzOw',
    appId: '1:346179915616:ios:84887e0ba77c2e5c8d5805',
    messagingSenderId: '346179915616',
    projectId: 'ecommerce-2c6ff',
    storageBucket: 'ecommerce-2c6ff.firebasestorage.app',
    iosClientId: '346179915616-20in463ma3d7u66v41ug92281kthmq8a.apps.googleusercontent.com',
    iosBundleId: 'com.app.aiassistant.ecommerce',
  );
}
